# Generated by Django 4.0.6 on 2022-07-22 08:34

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default='', max_length=7, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ranges', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='UserDataRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_ranges', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('meeting_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.meeting')),
            ],
        ),
    ]
