# Generated by Django 4.0.6 on 2022-07-22 08:51

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20220722_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), null=True, size=None),
        ),
    ]
