# Generated by Django 4.0.6 on 2022-07-27 10:37

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_auto_20220722_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdatarange',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.meeting'),
        ),
        migrations.AlterField(
            model_name='userdatarange',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
