# Generated by Django 4.0.6 on 2022-08-02 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_meeting_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
