# Generated by Django 4.0.6 on 2022-07-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_meeting_ranges_alter_userdatarange_meeting_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatarange',
            name='meeting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='calendarapp.meeting'),
        ),
    ]
