# Generated by Django 4.0.6 on 2022-07-22 13:07

import calendarapp.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_alter_meeting_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='ranges',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=calendarapp.models.next_ten_years), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='userdatarange',
            name='user_ranges',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=calendarapp.models.next_ten_years),
        ),
    ]
